# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
_anaconda_depends=2020.07=py37_0
_ipyw_jlab_nb_ext_conf=0.1.0=py37_0
_libgcc_mutex=0.1=main
absl-py=1.0.0=pypi_0
aiohttp=3.8.1=pypi_0
aiosignal=1.2.0=pypi_0
alabaster=0.7.12=py37_0
altair=4.1.0=pypi_0
anaconda=custom=py37_1
anaconda-client=1.7.2=py37_0
anaconda-navigator=1.9.12=py37_0
anaconda-project=0.8.4=py_0
appdirs=1.4.4=pypi_0
argh=0.26.2=py37_0
argon2-cffi=20.1.0=py37h7b6447c_1
ase=3.21.1=pypi_0
asn1crypto=1.4.0=py_0
astor=0.8.1=pypi_0
astroid=2.4.2=py37_0
astropy=4.2=py37h27cfd23_0
async-timeout=4.0.1=pypi_0
async_generator=1.10=py37h28b3542_0
asynctest=0.13.0=pypi_0
atomicwrites=1.4.0=py_0
attrs=20.3.0=pyhd3eb1b0_0
autocorrect=1.0.0=pypi_0
autopep8=1.5.4=py_0
babel=2.9.0=pyhd3eb1b0_0
backcall=0.2.0=py_0
backports=1.0=pyhd3eb1b0_2
backports-zoneinfo=0.2.1=pypi_0
backports.functools_lru_cache=1.6.1=pyhd3eb1b0_0
backports.shutil_get_terminal_size=1.0.0=py37_2
backports.tempfile=1.0=py_1
backports.weakref=1.0.post1=py_1
base58=2.1.1=pypi_0
beautifulsoup4=4.9.3=pyhb0f4dca_0
bert-serving=0.0.1=pypi_0
bert-serving-client=1.10.0=pypi_0
bert-serving-server=1.10.0=pypi_0
bitarray=1.6.1=py37h27cfd23_0
bkcharts=0.2=py37_0
blas=1.0=mkl
bleach=3.2.1=py_0
blessings=1.7=pypi_0
blinker=1.4=pypi_0
blis=0.4.1=pypi_0
blosc=1.20.1=hd408876_0
bokeh=2.2.3=py37_0
boto=2.49.0=py37_0
boto3=1.12.34=pypi_0
botocore=1.15.34=pypi_0
bottleneck=1.3.2=py37heb32a55_1
brotli=1.0.9=he6710b0_2
brotlipy=0.7.0=py37h27cfd23_1003
bzip2=1.0.8=h7b6447c_0
ca-certificates=2020.12.5=ha878542_0
cachetools=4.2.4=pypi_0
cairo=1.14.12=h8948797_3
catalogue=1.0.0=pypi_0
certifi=2020.12.5=py37h89c1867_1
cffi=1.14.4=py37h261ae71_0
chardet=3.0.4=py37h06a4308_1003
charls=2.1.0=he6710b0_2
charset-normalizer=2.0.9=pypi_0
clean-text=0.2.1=pypi_0
click=7.1.2=py_0
click-config-file=0.6.0=pypi_0
click-plugins=1.1.1=pypi_0
cloudpickle=1.6.0=py_0
clyent=1.2.2=py37_1
colorama=0.4.4=pyhd3eb1b0_0
conda=4.9.2=py37h89c1867_0
conda-build=3.18.11=py37_0
conda-env=2.6.0=1
conda-package-handling=1.7.2=py37h03888b9_0
conda-verify=3.4.2=py_1
configobj=5.0.6=pypi_0
configparser=5.2.0=pypi_0
contextlib2=0.6.0.post1=py_0
convokit=2.3.2.5=pypi_0
cryptography=3.3.1=py37h3c74f83_0
cudatoolkit=11.0.221=h6bb024c_0
curl=7.71.1=hbc83047_1
cycler=0.10.0=py37_0
cymem=2.0.3=pypi_0
cython=0.29.21=py37h2531618_0
cytoolz=0.11.0=py37h7b6447c_0
dask=2020.12.0=pyhd3eb1b0_0
dask-core=2020.12.0=pyhd3eb1b0_0
datasets=1.16.1=pypi_0
dbus=1.13.18=hb2f20db_0
decorator=4.4.2=py_0
defusedxml=0.6.0=py_0
diff-match-patch=20200713=py_0
dill=0.3.4=pypi_0
distributed=2020.12.0=py37h06a4308_0
docker-pycreds=0.4.0=pypi_0
docutils=0.15.2=pypi_0
emoji=1.2.0=pypi_0
en-core-web-sm=2.3.1=pypi_0
entrypoints=0.3=py37_0
et_xmlfile=1.0.1=py_1001
expat=2.2.10=he6710b0_2
fastai=2.6.3=pypi_0
fastcache=1.1.0=py37h7b6447c_0
fastcore=1.4.2=pypi_0
fastdownload=0.0.5=pypi_0
fastprogress=0.2.4=pypi_0
filelock=3.0.12=py_0
fire=0.4.0=pypi_0
flake8=3.8.4=py_0
flask=1.1.2=py_0
fontconfig=2.13.0=h9420a91_0
freetype=2.10.4=h5ab3b9f_0
fribidi=1.0.10=h7b6447c_0
frozenlist=1.2.0=pypi_0
fsspec=2021.11.1=pypi_0
ftfy=5.8=pypi_0
future=0.18.2=py37_1
get_terminal_size=1.0.0=haa9412d_0
gevent=20.9.0=py37h7b6447c_0
giflib=5.1.4=h14c3975_1
gitdb=4.0.9=pypi_0
gitpython=3.1.24=pypi_0
glib=2.66.1=h92f7085_0
glob2=0.7=py_0
gmp=6.1.2=h6c8ec71_1
gmpy2=2.0.8=py37h10f8cd9_2
google-auth=2.3.3=pypi_0
google-auth-oauthlib=0.4.6=pypi_0
googledrivedownloader=0.4=pypi_0
gpustat=0.6.0=pypi_0
gputil=1.4.0=pypi_0
graphite2=1.3.14=h23475e2_0
greenlet=0.4.17=py37h7b6447c_0
grpcio=1.42.0=pypi_0
gst-plugins-base=1.14.0=hbbd80ab_1
gstreamer=1.14.0=hb31296c_0
h5py=2.10.0=py37h7918eee_0
harfbuzz=2.4.0=hca77d97_1
hdf5=1.10.4=hb1b8bf9_0
heapdict=1.0.1=py_0
html5lib=1.1=py_0
huggingface-hub=0.2.1=pypi_0
humanize=3.12.0=pypi_0
icu=58.2=he6710b0_3
idna=2.8=pypi_0
imagecodecs=2020.5.30=py37hfa7d478_2
imageio=2.9.0=py_0
imagesize=1.2.0=py_0
importlib-metadata=4.8.2=pypi_0
importlib_metadata=2.0.0=1
iniconfig=1.1.1=py_0
intel-openmp=2020.2=254
intervaltree=3.1.0=py_0
ipykernel=5.3.4=py37h5ca1d4c_0
ipython=7.19.0=py37hb070fc8_0
ipython_genutils=0.2.0=pyhd3eb1b0_1
ipywidgets=7.5.1=py_1
isodate=0.6.0=pypi_0
isort=5.6.4=py_0
itsdangerous=1.1.0=py37_0
jbig=2.1=hdba287a_0
jdcal=1.4.1=py_0
jedi=0.14.1=py37_0
jeepney=0.6.0=pyhd3eb1b0_0
jinja2=2.11.2=py_0
jmespath=0.9.5=pypi_0
joblib=0.17.0=py_0
jpeg=9b=h024ee3a_2
json5=0.9.5=py_0
jsonschema=3.2.0=py_2
jupyter=1.0.0=py37_7
jupyter-contrib-core=0.3.3=pypi_0
jupyter_client=6.1.7=py_0
jupyter_console=6.2.0=py_0
jupyter_contrib_core=0.3.3=py_2
jupyter_contrib_nbextensions=0.5.1=pyhd8ed1ab_2
jupyter_core=4.7.0=py37h06a4308_0
jupyter_highlight_selected_word=0.2.0=py37h89c1867_1002
jupyter_latex_envs=1.4.6=pyhd8ed1ab_1002
jupyter_nbextensions_configurator=0.4.1=py37h89c1867_2
jupyterlab=2.2.6=py_0
jupyterlab_pygments=0.1.2=py_0
jupyterlab_server=1.2.0=py_0
jxrlib=1.1=h7b6447c_2
keyring=21.4.0=py37_1
kiwisolver=1.3.0=py37h2531618_0
krb5=1.18.2=h173b8e3_0
lazy-object-proxy=1.4.3=py37h27cfd23_2
lcms2=2.11=h396b838_0
ld_impl_linux-64=2.33.1=h53a641e_7
libaec=1.0.4=he6710b0_1
libarchive=3.4.2=h62408e4_0
libcurl=7.71.1=h20c2e04_1
libedit=3.1.20191231=h14c3975_1
libffi=3.3=he6710b0_2
libgcc-ng=9.1.0=hdf63c60_0
libgfortran-ng=7.3.0=hdf63c60_0
liblief=0.10.1=he6710b0_0
libllvm10=10.0.1=hbcb73fb_5
libllvm9=9.0.1=h4a3c616_1
libpng=1.6.37=hbc83047_0
libsodium=1.0.18=h7b6447c_0
libspatialindex=1.9.3=he6710b0_0
libssh2=1.9.0=h1ba5d50_1
libstdcxx-ng=9.1.0=hdf63c60_0
libtiff=4.1.0=h2733197_1
libtool=2.4.6=h7b6447c_1005
libuuid=1.0.3=h1bed415_2
libuv=1.40.0=h7b6447c_0
libwebp=1.0.1=h8e7db2f_0
libxcb=1.14=h7b6447c_0
libxml2=2.9.10=hb55368b_3
libxslt=1.1.34=hc22bd24_0
libzopfli=1.0.3=he6710b0_0
liwc=0.5.0=pypi_0
liwc-analysis=1.2.4=pypi_0
llvmlite=0.34.0=py37h269e1b5_4
locket=0.2.0=py37_1
lxml=4.6.2=py37h9120a33_0
lz4-c=1.9.2=heb0550a_3
lzo=2.10=h7b6447c_2
markdown=3.3.6=pypi_0
markupsafe=1.1.1=py37h14c3975_1
matplotlib=3.3.2=0
matplotlib-base=3.3.2=py37h817c723_0
mccabe=0.6.1=py37_1
mistune=0.8.4=py37h14c3975_1001
mkl=2020.2=256
mkl-service=2.3.0=py37he8ac12f_0
mkl_fft=1.2.0=py37h23d657b_0
mkl_random=1.1.1=py37h0573a6f_0
mock=4.0.3=pyhd3eb1b0_0
more-itertools=8.6.0=pyhd3eb1b0_0
mpc=1.1.0=h10f8cd9_1
mpfr=4.0.2=hb69a4c5_1
mpmath=1.1.0=py37_0
msgpack-numpy=0.4.6.1=pypi_0
msgpack-python=1.0.0=py37hfd86e86_1
multidict=5.2.0=pypi_0
multipledispatch=0.6.0=py37_0
multiprocess=0.70.12.2=pypi_0
murmurhash=1.0.2=pypi_0
mwparserfromhell=0.5.4=pypi_0
navigator-updater=0.2.1=py37_0
nbclient=0.5.1=py_0
nbconvert=6.0.7=py37_0
nbformat=5.0.7=py_0
ncurses=6.2=he6710b0_1
nest-asyncio=1.4.3=pyhd3eb1b0_0
networkx=2.5=py_0
ninja=1.10.2=py37hff7bd54_0
nltk=3.5=py_0
nose=1.3.7=pyhd3eb1b0_1006
notebook=6.1.4=py37_0
numba=0.51.2=py37h04863e7_1
numexpr=2.7.1=py37h63df603_0
numpy=1.19.2=py37h54aff64_0
numpy-base=1.19.2=py37hfa32c7d_0
numpydoc=1.1.0=pyhd3eb1b0_1
nvidia-ml-py3=7.352.0=pypi_0
oauthlib=3.2.2=pypi_0
olefile=0.46=py37_0
openjpeg=2.3.0=h05c96fa_1
openpyxl=3.0.5=py_0
openssl=1.1.1k=h27cfd23_0
packaging=21.3=pypi_0
pandas=1.1.3=py37he6710b0_0
pandoc=2.11=hb0f4dca_0
pandocfilters=1.4.3=py37h06a4308_1
pango=1.45.3=hd140c19_0
parso=0.5.2=py_0
partd=1.1.0=py_0
patchelf=0.12=h2531618_1
path=15.0.1=py37h06a4308_0
path.py=12.5.0=0
pathlib2=2.3.5=py37h06a4308_2
pathtools=0.1.2=py_1
patsy=0.5.1=py37_0
pcre=8.44=he6710b0_0
pep8=1.7.1=py37_0
pexpect=4.8.0=pyhd3eb1b0_3
pickleshare=0.7.5=pyhd3eb1b0_1003
pillow=8.0.1=py37he98fc37_0
pip=20.3.1=py37h06a4308_0
pip-autoremove=0.9.1=pypi_0
pixman=0.40.0=h7b6447c_0
pkginfo=1.6.1=py37h06a4308_0
plac=1.1.3=pypi_0
pluggy=0.13.1=py37_0
ply=3.11=py37_0
powerlaw=1.4.6=pypi_0
preshed=3.0.2=pypi_0
prometheus_client=0.9.0=pyhd3eb1b0_0
promise=2.3=pypi_0
prompt-toolkit=3.0.8=py_0
prompt_toolkit=3.0.8=0
protobuf=3.19.1=pypi_0
psutil=5.7.2=py37h7b6447c_0
ptyprocess=0.6.0=pyhd3eb1b0_2
py=1.9.0=py_0
py-lief=0.10.1=py37h403a769_0
pyarrow=6.0.1=pypi_0
pyasn1=0.4.8=pypi_0
pyasn1-modules=0.2.8=pypi_0
pycocoevalcap=1.2=pypi_0
pycocotools=2.0.4=pypi_0
pycodestyle=2.6.0=py_0
pycosat=0.6.3=py37h27cfd23_0
pycparser=2.20=py_2
pycrypto=2.6.1=py37h7b6447c_10
pycurl=7.43.0.6=py37h1ba5d50_0
pydeck=0.7.1=pypi_0
pydocstyle=5.1.1=py_0
pyerfa=1.7.1.1=py37h27cfd23_1
pyflakes=2.2.0=py_0
pygments=2.7.3=pyhd3eb1b0_0
pylint=2.6.0=py37_0
pympler=0.9=pypi_0
pyodbc=4.0.30=py37he6710b0_0
pyopenssl=20.0.0=pyhd3eb1b0_1
pyparsing=2.4.7=py_0
pyphen=0.10.0=pypi_0
pyqt=5.9.2=py37h05f1152_2
pyrsistent=0.17.3=py37h7b6447c_0
pyshorteners=1.0.1=pypi_0
pysocks=1.7.1=py37_1
pytables=3.6.1=py37h71ec239_0
pytest=6.1.2=py37h06a4308_0
python=3.7.6=h0371630_2
python-dateutil=2.8.1=py_0
python-jsonrpc-server=0.4.0=py_0
python-language-server=0.31.7=py37_0
python-levenshtein=0.12.0=pypi_0
python-libarchive-c=2.9=py_0
python-louvain=0.15=pypi_0
python_abi=3.7=1_cp37m
pytorch=1.7.1=py3.7_cuda11.0.221_cudnn8.0.5_0
pytorch-pretrained-bert=0.6.2=pypi_0
pytz=2020.4=pyhd3eb1b0_0
pytz-deprecation-shim=0.1.0.post0=pypi_0
pywavelets=1.1.1=py37h7b6447c_2
pyxdg=0.27=pyhd3eb1b0_0
pyyaml=5.3.1=py37h7b6447c_1
pyzmq=20.0.0=py37h2531618_1
qdarkstyle=2.8.1=py_0
qt=5.9.7=h5867ecd_1
qtawesome=1.0.1=py_0
qtconsole=4.7.7=py_0
qtpy=1.9.0=py_0
rdflib=5.0.0=pypi_0
readline=7.0=h7b6447c_5
regex=2017.4.5=pypi_0
requests=2.28.2=pypi_0
requests-oauthlib=1.3.0=pypi_0
ripgrep=12.1.1=0
rope=0.18.0=py_0
rsa=4.8=pypi_0
rtree=0.9.4=py37_1
ruamel_yaml=0.15.87=py37h7b6447c_1
s3transfer=0.3.3=pypi_0
sacremoses=0.0.41=pypi_0
scikit-image=0.17.2=py37hdf5156a_0
scikit-learn=0.23.2=py37h0573a6f_0
scipy=1.5.2=py37h0b6359f_0
seaborn=0.11.0=py_0
secretstorage=3.3.0=py37h06a4308_0
send2trash=1.5.0=pyhd3eb1b0_1
sentencepiece=0.1.85=pypi_0
sentry-sdk=1.5.1=pypi_0
seqeval=1.2.2=pypi_0
setuptools=51.0.0=py37h06a4308_2
shortuuid=1.0.8=pypi_0
simplediff=1.0=pypi_0
simplegeneric=0.8.1=py37_2
simpletransformers=0.63.3=pypi_0
singledispatch=3.4.0.3=py_1001
sip=4.19.8=py37hf484d3e_0
six=1.15.0=py37h06a4308_0
sklearn=0.0=pypi_0
smmap=5.0.0=pypi_0
snappy=1.1.8=he6710b0_0
snowballstemmer=2.0.0=py_0
sortedcollections=1.2.1=py_0
sortedcontainers=2.3.0=pyhd3eb1b0_0
soupsieve=2.0.1=py_0
spacy=2.3.2=pypi_0
sphinx=3.2.1=py_0
sphinxcontrib=1.0=py37_1
sphinxcontrib-applehelp=1.0.2=py_0
sphinxcontrib-devhelp=1.0.2=py_0
sphinxcontrib-htmlhelp=1.0.3=py_0
sphinxcontrib-jsmath=1.0.1=py_0
sphinxcontrib-qthelp=1.0.3=py_0
sphinxcontrib-serializinghtml=1.1.4=py_0
sphinxcontrib-websupport=1.2.4=py_0
spyder=4.0.1=py37_0
spyder-kernels=1.8.1=py37_0
sqlalchemy=1.3.20=py37he8ac12f_0
sqlite=3.33.0=h62c20be_0
srsly=1.0.2=pypi_0
statsmodels=0.12.1=py37h27cfd23_0
streamlit=1.2.0=pypi_0
subprocess32=3.5.4=pypi_0
sympy=1.6.2=py37h06a4308_1
tbb=2020.3=hfd86e86_0
tblib=1.7.0=py_0
tensorboard=2.7.0=pypi_0
tensorboard-data-server=0.6.1=pypi_0
tensorboard-plugin-wit=1.8.0=pypi_0
tensorboardx=2.0=pypi_0
termcolor=1.1.0=pypi_0
terminado=0.9.1=py37_0
testpath=0.4.4=py_0
textstat=0.7.0=pypi_0
thinc=7.4.1=pypi_0
threadpoolctl=2.1.0=pyh5ca1d4c_0
tifffile=2020.12.4=pyhd3eb1b0_0
tk=8.6.10=hbc83047_0
tokenizers=0.5.2=pypi_0
toml=0.10.1=py_0
toolz=0.11.1=py_0
toposort=1.5=pypi_0
torch=1.4.0=pypi_0
torch-geometric=1.7.0=pypi_0
torch-scatter=2.0.6=pypi_0
torch-sparse=0.6.9=pypi_0
torchaudio=0.7.2=py37
torchvision=0.5.0=pypi_0
tornado=6.1=py37h27cfd23_0
tqdm=4.62.3=pypi_0
traitlets=5.0.5=py_0
transformers=2.7.0=pypi_0
twarc=2.8.1=pypi_0
tweepy=4.12.1=pypi_0
twython=3.8.2=pypi_0
typed-ast=1.4.1=py37h7b6447c_0
typing_extensions=3.7.4.3=py_0
tzdata=2021.5=pypi_0
tzlocal=4.1=pypi_0
ujson=4.0.1=py37he6710b0_0
unicodecsv=0.14.1=py37_0
unidecode=1.1.1=pypi_0
unixodbc=2.3.9=h7b6447c_0
unshortenit=0.4.0=pypi_0
uritools=3.0.0=pypi_0
urlextract=1.0.0=pypi_0
urllib3=1.24.3=pypi_0
vadersentiment=3.3.2=pypi_0
validators=0.18.2=pypi_0
wandb=0.12.7=pypi_0
wasabi=0.7.1=pypi_0
watchdog=0.10.4=py37h06a4308_0
wcwidth=0.2.5=py_0
webencodings=0.5.1=py37_1
werkzeug=1.0.1=py_0
wheel=0.36.1=pyhd3eb1b0_0
widgetsnbextension=3.5.1=py37_0
wikipedia-api=0.5.4=pypi_0
wrapt=1.11.2=py37h7b6447c_0
wurlitzer=2.0.1=py37_0
xlrd=1.2.0=py37_0
xlsxwriter=1.3.7=py_0
xlwt=1.3.0=py37_0
xmltodict=0.12.0=py_0
xxhash=2.0.2=pypi_0
xz=5.2.5=h7b6447c_0
yaml=0.2.5=h7b6447c_0
yapf=0.30.0=py_0
yarl=1.7.2=pypi_0
yaspin=2.1.0=pypi_0
zeromq=4.3.3=he6710b0_3
zict=2.0.0=py_0
zipp=3.4.0=pyhd3eb1b0_0
zlib=1.2.11=h7b6447c_3
zope=1.0=py37_1
zope.event=4.5.0=py37_0
zope.interface=5.2.0=py37h27cfd23_0
zstd=1.4.5=h9ceee32_0
